# Generated by Django 6.0.4 on 2026-05-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
    ]
