# Generated by Django 6.0.4 on 2026-05-05 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_flexible_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['session', 'type'], name='cash_mov_session_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['created_at'], name='cash_mov_created_at_idx'),
        ),
    ]
