# Generated by Django 6.0.4 on 2026-05-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_cashmovement_cash_mov_session_type_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='auto_closed',
            field=models.BooleanField(default=False, help_text='True si la sesión fue cerrada automáticamente por el sistema a la medianoche'),
        ),
    ]
