# Generated by Django 6.0.4 on 2026-04-15 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('points_used', models.PositiveIntegerField(default=0)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('debit', 'Tarjeta Débito'), ('credit', 'Tarjeta Crédito'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('other', 'Otro')], max_length=10)),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.cashsession')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('return', 'Devolución'), ('swap', 'Cambio')], max_length=10)),
                ('reason', models.CharField(choices=[('damaged', 'Prenda dañada'), ('size', 'Talla incorrecta'), ('order', 'Encargo no aceptado'), ('other', 'Otro')], max_length=10)),
                ('returned_quantity', models.PositiveIntegerField()),
                ('returned_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('swapped_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('swapped_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.cashsession')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('returned_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.productvariant')),
                ('swapped_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='swaps', to='inventory.productvariant')),
                ('original_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
            ],
        ),
    ]
