# Generated by Django 6.0.4 on 2026-05-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_add_order_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
