# Generated by Django 6.0.4 on 2026-05-05 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_cashmovement_cash_mov_session_type_idx_and_more'),
        ('customers', '0002_customer_customer_created_at_idx'),
        ('orders', '0002_order_order_status_date_idx_and_more'),
        ('sales', '0003_flexible_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sale_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_method'], name='sale_payment_method_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_by', 'created_at'], name='sale_seller_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'created_at'], name='sale_customer_date_idx'),
        ),
    ]
