# Generated by Django 6.0.4 on 2026-04-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('points_per_amount', models.DecimalField(decimal_places=2, default=1000, help_text='Cada X pesos = 1 punto', max_digits=10)),
                ('value_per_point', models.DecimalField(decimal_places=2, default=50, help_text='Cada punto vale X pesos de descuento', max_digits=10)),
                ('min_points_redeem', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Loyalty Config',
            },
        ),
    ]
