# Generated by Django 6.0.4 on 2026-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customer_created_at_idx'),
        ),
    ]
