# Generated by Django 6.0.4 on 2026-04-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
