# Generated by Django 6.0.4 on 2026-04-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('primary_color', models.CharField(default='#2E86C1', max_length=7)),
                ('whatsapp', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('return_policy', models.TextField(blank=True)),
                ('banner_text', models.CharField(blank=True, max_length=300)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('msg_in_progress', models.TextField(default='Hola {nombre_cliente}, ya recibimos tu pedido #{numero_pedido} y lo estamos gestionando. 😊')),
                ('msg_confirmed', models.TextField(default='¡{nombre_cliente}, tu pedido #{numero_pedido} está confirmado! Total: {total}. Te avisamos cuando esté listo.')),
                ('msg_preparing', models.TextField(default='Hola {nombre_cliente}, tu pedido #{numero_pedido} está siendo preparado. 📦')),
                ('msg_shipped', models.TextField(default='¡{nombre_cliente}, tu pedido #{numero_pedido} fue enviado! Pronto lo recibirás. 🚚')),
                ('msg_delivered', models.TextField(default='Hola {nombre_cliente}, tu pedido #{numero_pedido} fue entregado. ¡Gracias por tu compra! 🛍️')),
                ('msg_cancelled', models.TextField(default='Hola {nombre_cliente}, lamentamos informarte que tu pedido #{numero_pedido} fue cancelado. Escríbenos para más información.')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
            },
        ),
    ]
