# Generated by Django 6.0.4 on 2026-04-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_storeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Lista de métodos de pago configurados para la tienda.'),
        ),
    ]
